CREATE DATABASE IF NOT EXISTS ci_buku;

USE ci_buku;

CREATE TABLE IF NOT EXISTS books(
	id INT AUTO_INCREMENT PRIMARY KEY,
	judul VARCHAR(255) NOT NULL,
	penulis VARCHAR(255) NOT NULL,
	tahun_terbit INT NOT NULL
);
